// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzTtGky8QOTH-MylvO-vobfsO1WTzXoTM',
    appId: '1:370932220907:web:889ca1080dc9a8aecb8fae',
    messagingSenderId: '370932220907',
    projectId: 'lenguajedesenas-f1e6d',
    authDomain: 'lenguajedesenas-f1e6d.firebaseapp.com',
    storageBucket: 'lenguajedesenas-f1e6d.appspot.com',
    measurementId: 'G-YZ6TQF73L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrVKbGWEHgPhIMUh5irTZohtOgEqh_d60',
    appId: '1:370932220907:android:789df82777dd9e06cb8fae',
    messagingSenderId: '370932220907',
    projectId: 'lenguajedesenas-f1e6d',
    storageBucket: 'lenguajedesenas-f1e6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChpweKsSzt0fr3c0Hd56C5KCeMb1Trnc4',
    appId: '1:370932220907:ios:e7873dfc1c970da3cb8fae',
    messagingSenderId: '370932220907',
    projectId: 'lenguajedesenas-f1e6d',
    storageBucket: 'lenguajedesenas-f1e6d.appspot.com',
    iosClientId: '370932220907-2ptqtde6o52ktokq0o3kfb5co5c6irgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.lenguajeDeSenasProyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChpweKsSzt0fr3c0Hd56C5KCeMb1Trnc4',
    appId: '1:370932220907:ios:c4a99f60bcb306afcb8fae',
    messagingSenderId: '370932220907',
    projectId: 'lenguajedesenas-f1e6d',
    storageBucket: 'lenguajedesenas-f1e6d.appspot.com',
    iosClientId: '370932220907-oenq16d4hiutcpr3v25mpjt4dsjft0vi.apps.googleusercontent.com',
    iosBundleId: 'com.example.lenguajeDeSenasProyecto.RunnerTests',
  );
}
